[package]
name = "bikelang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
indexmap = "1.9.2"
itertools = "0.10.5"
thiserror = "1.0.38"
